version: '3.8'
services:

  db:
    image: "postgres:13.1"
    container_name: "postgres"
    volumes:
     - db:/var/lib/postgresql/data
    ports:
     - 5432:5432
    environment:
     - POSTRGRES_DB:postgres
     - POSTGRES_USER:postgres
     - POSTGRES_PASSWORD:postgres

  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/api
    environment:
     - DB_SERVER=db
    ports:
     - 3000:3000
    links:
      - db

  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/client
    ports:
     - 8000:8000
    links:
     - api

volumes:
  db:
